repository:
  allow_auto_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  allow_update_branch: true
  default_branch: main
  delete_branch_on_merge: true
  description: Install Lix faster than you can refresh a GitHub Actions workflow page
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_issues: true
  has_projects: false
  has_wiki: false
  homepage: https://github.com/fabrictest/action-setup-lix
  is_template: false
  merge_commit_message: PR_BODY
  merge_commit_title: PR_TITLE
  name: action-setup-lix
  security_and_analysis: null
  squash_merge_commit_message: PR_BODY
  squash_merge_commit_title: PR_TITLE
  topics: github-actions,lix,nix
  visibility: public
rulesets:
- conditions:
    ref_name:
      include:
      - ~DEFAULT_BRANCH
  enforcement: active
  name: Prevent tampering with default branch
  rules:
  - type: deletion
  - type: non_fast_forward
  - type: required_linear_history
  target: branch
- conditions:
    ref_name:
      include:
      - ~DEFAULT_BRANCH
  enforcement: active
  name: Require PRs to pass the quality bar
  rules:
  - parameters:
      check_response_timeout_minutes: 60
      grouping_strategy: ALLGREEN
      max_entries_to_build: 5
      max_entries_to_merge: 5
      merge_method: SQUASH
      min_entries_to_merge: 1
      min_entries_to_merge_wait_minutes: 5
    type: merge_queue
  - parameters:
      allowed_merge_methods:
      - squash
      automatic_copilot_code_review_enabled: true
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: true
      require_last_push_approval: true
      required_approving_review_count: 1
      required_review_thread_resolution: true
    type: pull_request
  - parameters:
      required_status_checks:
      - context: Test / Examples (2.90.0, macos-13)
        integration_id: 15368
      - context: Test / Examples (2.90.0, macos-15)
        integration_id: 15368
      - context: Test / Examples (2.90.0, ubuntu-24.04)
        integration_id: 15368
      - context: Test / Examples (2.91.1, macos-13)
        integration_id: 15368
      - context: Test / Examples (2.91.1, macos-15)
        integration_id: 15368
      - context: Test / Examples (2.91.1, ubuntu-24.04)
        integration_id: 15368
      - context: Test / With Cachix (2.90.0, macos-13)
        integration_id: 15368
      - context: Test / With Cachix (2.90.0, macos-15)
        integration_id: 15368
      - context: Test / With Cachix (2.90.0, ubuntu-24.04)
        integration_id: 15368
      - context: Test / With Cachix (2.91.1, macos-13)
        integration_id: 15368
      - context: Test / With Cachix (2.91.1, macos-15)
        integration_id: 15368
      - context: Test / With Cachix (2.91.1, ubuntu-24.04)
        integration_id: 15368
      strict_required_status_checks_policy: false
    type: required_status_checks
  target: branch
- conditions:
    ref_name:
      include:
      - refs/tags/v*
  enforcement: active
  name: Prevent deletion of release tags
  rules:
  - type: deletion
  target: tag
- conditions:
    ref_name:
      include:
      - refs/tags/v*.*.*
  enforcement: active
  name: Prevent tampering with release tags
  rules:
  - type: non_fast_forward
  - type: update
  target: tag
