bypass_actors: []
repository:
  description: Install Lix on GitHub Actions faster than you can refresh your browser
  homepage: https://github.com/fabrictest/action-setup-lix
  name: action-setup-lix
rulesets: []
