---
name: action-setup-lix
description: Install Lix on GitHub Actions faster than you can refresh your browser
author: F. Emerson
inputs:
  lix-version:
    description: |
      The version of Lix that should be installed.

      If not specified, the latest stable Lix release is used. Note that each
      release of action-setup-lix has a specific set of supported
      Lix versions, which do not change. You can check what Lix versions are
      supported by the version of action-setup-lix you're using by
      going to https://github.com/fabrictest/action-setup-lix/releases.
    required: false
  nix-conf:
    description: |
      If set, this configuration is written to $XDG_CONFIG_HOME/nix/nix.conf,
      which is read by Lix.
      See https://docs.lix.systems/manual/lix/stable/command-ref/conf-file.html for
      information on what settings that are available. Make sure the settings
      you define are supported by the Lix version you're using.
    required: false
  github-token:
    description: |
      Configure Lix to use the specified token when fetching from GitHub.
      Defaults to `github.token`.
    default: ${{ github.token }}
  lix-on-tmpfs:
    description: |
      Installs /nix on a tmpfs mount. This can make Lix operations faster, but
      you risk running out of memory if your Lix store grows too big. Only
      enable this if you're absolutely sure the size of your Lix store (and
      database, logs etc) will be considerably less than the available memory.
      This option does nothing on MacOS runners.
    default: false
  lix-store-base-url:
    description: |
      Internal.
    required: false
runs:
  using: composite
  steps:
    - name: Do preflight checks
      id: checks
      shell: bash
      env:
        LIX_VERSION: ${{ inputs.lix-version }}
        # renovate: datasource=github-tags depName=lix-project/lix
        LIX_DEFAULT_VERSION: 2.91.1
      run: |
        :
        set -x
        printf '::group::Preflight checks\n'
        test ! -e /nix -o -w /nix || {
          printf "::error::failed to set up Lix: /nix exists but isn't writable\n"
          exit 1
        }
        test -n "$LIX_VERSION" || unset LIX_VERSION
        tee -a "$GITHUB_OUTPUT" <<EOF
        install-nix-dir=$(test -e /nix || printf 1)
        our-version=$(cat "$GITHUB_ACTION_PATH"/VERSION)
        lix-version=${LIX_VERSION:-$LIX_DEFAULT_VERSION}
        EOF
        printf '::endgroup::\n'
    - name: Mount `/nix` directory (Linux)
      if: ${{ steps.checks.outputs.install-nix-dir && runner.os == 'Linux' }}
      shell: bash
      run: |
        :
        set -x
        printf '::group::Mount `/nix` directory\n'
        sudo install -d -o "$USER" /nix
        ${{
          inputs.lix-on-tmpfs &&
              'sudo mount -t tmpfs -o "size=90%,mode=0755,uid=$UID,gid=$(id -g)" tmpfs /nix' ||
              ''
        }}
        printf '::endgroup::\n'
    - name: Mount `/nix` directory (macOS)
      if: ${{ steps.checks.outputs.install-nix-dir && runner.os == 'macOS' }}
      shell: bash
      run: |
        :
        set -x
        printf '::group::Mount `/nix` directory\n'
        sudo tee -a /etc/synthetic.conf <<"EOF"
        nix
        run	private/var/run
        EOF
        sudo /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t || :
        test -L /run || {
          printf "::error::failed to set up Lix: apfs.util couldn't symlink /run\n"
          exit 1
        }
        root_device=$(stat -f %Sd /)
        sudo diskutil apfs addVolume "${root_device%s*}" APFS nix -mountpoint /nix
        sudo mdutil -i off /nix
        sudo chown "$USER" /nix
        printf '::endgroup::\n'
    - name: Install Lix store
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        lix_store_url: >-
          ${{
            format('{0}/lix-{1}-{2}-{3}.tar.zstd',
                inputs.lix-store-base-url || format('{0}/{1}/releases/download/v{2}',
                        github.server_url,
                        github.action_repository,
                        steps.checks.outputs.our-version
                    ),
                steps.checks.outputs.lix-version,
                (runner.arch == 'ARM64' && 'aarch64') || (runner.arch == 'X64' && 'x86_64') || runner.arch,
                (runner.os == 'Linux' && 'linux') || (runner.os == 'macOS' && 'darwin') || runner.os
            )
          }}
      run: |
        :
        set -x
        printf '::group::Install Lix store\n'
        rm -rf /nix/var/action-setup-lix
        ${{
          !startsWith(inputs.lix-store-base-url, 'file://') &&
              'curl --fail --location --remote-name --retry-connrefused --silent --show-error --retry 3 "$lix_store_url"' ||
              ''
        }}
        lix_store_file="${lix_store_url#${{ startsWith(inputs.lix-store-base-url, 'file://') && '*:/' || '#*' }}/}"
        gh attestation verify "$lix_store_file" --repo "$GITHUB_ACTION_REPOSITORY"
        ${{ runner.os == 'macOS' && 'g' || '' }}tar --auto-compress --extract --skip-old-files --directory=/nix --strip-components=1 "$lix_store_file"
        ${{
          !startsWith(inputs.lix-store-base-url, 'file://') &&
              'rm -rf "$lix_store_file"' ||
              ''
        }}
        printf '::endgroup::\n'
    - name: Synthesize `nix.conf`
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        nix_conf: ${{ inputs.nix-conf }}
      run: |
        :
        set -x
        printf '::group::Synthesize `nix.conf`\n'
        : "${XDG_CONFIG_HOME:=$HOME/.config}"
        mkdir -p "$XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID"
        tee "$XDG_CONFIG_HOME/nix/nix.conf" <<EOF
        accept-flake-config = true
        access-tokens = ${GITHUB_SERVER_URL#*://}=$GITHUB_TOKEN
        experimental-features = nix-command flakes
        include $XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID/nix.conf
        EOF
        tee "$XDG_CONFIG_HOME/nix/$GITHUB_REPOSITORY_ID/nix.conf" <<EOF
        $nix_conf
        EOF
        printf '::endgroup::\n'
    - name: Install Lix
      shell: bash
      run: |
        :
        set -x
        printf '::group::Install Lix\n'
        CDPATH='' cd "$(readlink /nix/var/action-setup-lix/lix)"
        ./bin/nix-store --load-db </nix/var/action-setup-lix/registration
        MANPATH='' . ./etc/profile.d/nix.sh
        : "${NIX_SSL_CERT_FILE:=$(test ! -e /etc/ssl/cert.pem || printf /etc/ssl/cert.pem)}"
        ./bin/nix-env --install "$PWD"
        printf %s/.nix-profile/bin\\n "$HOME" >>"$GITHUB_PATH"
        tee -a "$GITHUB_ENV" <<EOF
        NIX_PROFILES=/nix/var/nix/profiles/default $HOME/.nix-profile
        NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/$USER
        NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE
        EOF
        printf '::endgroup::\n'
branding:
  icon: package
  color: purple
