---
name: action-setup-lix
description: Install Lix on GitHub Actions faster than you can refresh your browser
author: F. Emerson
inputs:
  lix-version:
    description: |
      The version of Lix that should be installed.

      If not specified, the latest stable Lix release is used. Note that each
      release of action-setup-lix has a specific set of supported
      Lix versions, which do not change. You can check what Lix versions are
      supported by the version of action-setup-lix you're using by
      going to https://github.com/fabrictest/action-setup-lix/releases.
    required: false
  lix-on-tmpfs:
    description: |
      Installs /nix on a tmpfs mount. This can make Lix operations faster, but
      you risk running out of memory if your Lix store grows too big. Only
      enable this if you're absolutely sure the size of your Lix store (and
      database, logs etc) will be considerably less than the available memory.
      This option does nothing on MacOS runners.
    default: false
  nix-conf:
    description: |
      If set, this configuration is written to $XDG_CONFIG_HOME/nix/nix.conf,
      which is read by Lix.
      See https://docs.lix.systems/manual/lix/stable/command-ref/conf-file.html for
      information on what settings that are available. Make sure the settings
      you define are supported by the Lix version you're using.
    required: false
  github-token:
    description: |
      Configure Lix to use the specified token when fetching from GitHub.
      Defaults to `github.token`.
    default: ${{ github.token }}
  lix-stores-dir:
    description: |
      Internal.
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      run: ./action.bash
      env:
        # renovate: datasource=github-tags depName=lix-project/lix
        LIX_DEFAULT_VERSION: 2.91.1
        LIX_VERSION: ${{ inputs.lix-version || null }}
        LIX_ON_DISK: ${{ inputs.lix-on-tmpfs != 'true' || null }}
        NIX_CONF: ${{ inputs.nix-conf || null }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LIX_STORES_DIR: ${{ inputs.lix-stores-dir || null }}
branding:
  icon: package
  color: purple
