---
name: Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
  schedule:
    - cron: 33 01 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lix-stores:
    name: Build Lix stores
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - macos-13 # X64
          - macos-15 # ARM64
          - ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}
    permissions:
      attestations: write
      id-token: write
    steps:
      - name: Bootstrap Lix
        uses: fabrictest/action-setup-lix@a745987f4ef56ddcc1df9d7974cef54f0704ca46 # v0.3.0
        with:
          lix-on-tmpfs: true
      - name: Set up Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Build Lix stores
        run: |
          nix build .#lix-stores
        shell: bash
      - name: Attest Lix stores
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: result/lix-*.tar.*
      - name: Upload Lix stores to GitHub
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: lix-stores-${{ runner.os }}-${{ runner.arch }}
          path: result/lix-*.tar.*
      - name: Which Lix versions were built for this platform?
        run: |
          printf %s\\n result/lix-*.tar.* |
            cut -d- -f2 |
            jq --compact-output --raw-input --arg runs-on "$runs_on" \
              '{"lix-version": .} + $ARGS.named' >support-matrix-"$runs_on".ndjson
        shell: bash
        env:
          runs_on: ${{ matrix.runs-on }}
      - name: Upload support matrix files to GitHub
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: support-matrix-${{ matrix.runs-on }}
          path: support-matrix-${{ matrix.runs-on }}.ndjson
          compression-level: 9
          retention-days: 1
  support:
    name: Resolve support matrix
    needs:
      - lix-stores
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.json }}
    steps:
      - name: Download support matrix files
        id: matrix-files
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: support-matrix-*
          merge-multiple: true
      - name: Generate support matrix
        id: matrix
        run: |
          tee -a "$GITHUB_OUTPUT" <<EOF
          json<<JSON
          $(cat *.ndjson | jq --slurp '{support: .}')
          JSON
          EOF
        shell: bash
        working-directory: ${{ steps.matrix-files.outputs.download-path }}
  examples:
    name: Test examples
    needs:
      - support
    strategy:
      fail-fast: true
      matrix: ${{ fromjson(needs.support.outputs.matrix) }}
    runs-on: ${{ matrix.support.runs-on }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Download Lix store from GitHub
        id: lix-stores
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: lix-stores-${{ runner.os }}-${{ runner.arch }}
      - name: Install Lix ${{ matrix.support.lix-version }}
        uses: ./
        with:
          lix-on-tmpfs: true
          lix-store-dir: ${{ steps.lix-stores.outputs.download-path }}
          lix-version: ${{ matrix.support.lix-version }}
      - name: Verify that Lix was installed
        run: |
          nix-build -v --version
        shell: bash
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ vars.CACHIX_NAME }}
      - name: Build flake
        run: |
          nix build ./examples/flakes
        shell: bash
      - name: Print `hello, world` message
        run: |
          ./result/bin/hello
        shell: bash
