---
name: CD
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      id-token: write
  release:
    needs:
      - build
    name: Release
    uses: ./.github/workflows/release.yaml
    permissions:
      attestations: write
      id-token: write
    secrets:
      CICD_APP_ID: ${{ secrets.CICD_APP_ID }}
      CICD_PRIVATE_KEY: ${{ secrets.CICD_PRIVATE_KEY }}
