---
name: CD
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      attestations: write
      id-token: write
  publish:
    needs:
      - build
    name: Publish
    uses: ./.github/workflows/publish.yaml
    permissions:
      actions: read
      contents: write
      pull-requests: write
    secrets: inherit
