---
name: CI
on:
  merge_group:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "**"
  schedule:
    - cron: "33 01 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      attestations: write
      id-token: write
  test:
    needs:
      - build
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      build-matrix: ${{ needs.build.outputs.matrix }}
    secrets: inherit
