---
name: CI
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "**"
  schedule:
    - cron: "33 01 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    permissions:
      attestations: write
      id-token: write
  test:
    needs:
      - build
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      cachix-name: ${{ vars.CACHIX_NAME }}
      support-matrix: ${{ needs.build.outputs.support-matrix }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

