---
name: Examples / Flakes
on: workflow_dispatch
permissions: {}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: fabrictest/action-setup-lix@d5d7d9aa579140ff7b9b64c02766ed55bb80c3f8 # v0.15.0
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: fabrictest/action-setup-lix
          persist-credentials: false
      - run: nix build ./examples/flakes
      - run: ./result/bin/hello
