---
name: Examples / Minimal
on: workflow_dispatch
permissions: {}
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: fabrictest/action-setup-lix@d5d7d9aa579140ff7b9b64c02766ed55bb80c3f8 # v0.15.0
      - run: nix build --version
