---
name: Examples
on:
  push:
    branches:
      - main
jobs:
  flakes:
    name: Flakes
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - macos-13 # X64
          - macos-15 # ARM64
          - ubuntu-24.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Install Lix
        uses: fabrictest/action-setup-lix@def519a74f4b43c127a41d8d5eb28323ab485710 # v0.1.0
      - name: Print Lix version
        run: |
          nix-build -v --version
      - name: Set up Nix binary cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build flake
        run: |
          nix build ./examples/flakes
      - name: Print `hello, world` message
        run: |-
          ./result/bin/hello
