---
name: Examples
on:
  push:
    branches:
      - main
jobs:
  flakes:
    name: Flakes
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - macos-13
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install Lix
        uses: fabrictest/action-lix-quick-install@a26983acff7d1282354fdf48f1e4dcb883bfb85e # v7.3.0
      - name: Print Lix version
        run: |
          nix-build -v --version
      - name: Set up Nix binary cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build flake
        run: |
          nix build ./examples/flakes
      - name: Print `hello, world` message
        run: |-
          ./result/bin/hello
