---
name: Git tag sync
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions: {}
jobs:
  resolve:
    name: Resolve tags to synchronize
    if: ${{ github.event.created }}
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.json }}
    steps:
      - name: Which tags to synchronize?
        id: tags
        run: |
          {
            echo json'<<'JSON
            jq -Rcn '[inputs | select(length > 0)]' <<EOF
          ${GITHUB_REF_NAME%.*}
          ${GITHUB_REF_NAME%%.*}
          EOF
            echo JSON
          } >>"$GITHUB_OUTPUT"
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
  sync:
    name: Synchronize tag
    needs:
      - resolve
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJSON(needs.resolve.outputs.tags) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create tag object
        id: object
        run: |
          gh api repos/{owner}/{repo}/git/tags \
              -f tag="$tag" \
              -f message="$tag → $GITHUB_REF_NAME" \
              -f object="$GITHUB_SHA" \
              -f type=commit \
              -t 'sha={{.sha}}' >>"$GITHUB_OUTPUT"
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          tag: ${{ matrix.tag }}
      - name: Point reference to new tag object
        run: |
          gh api -X PATCH repos/{owner}/{repo}/git/refs/tags/"$tag" -f sha="$sha" ||
            gh api repos/{owner}/{repo}/git/refs -f ref=refs/tags/"$tag" -f sha="$sha"
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          tag: ${{ matrix.tag }}
          sha: ${{ steps.object.outputs.sha }}
