---
name: Release Please
on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    types:
      - completed
    branches:
      - main
    workflows:
      - Action / Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  update:
    name: Update release state
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.MADDERFERRYS_APP_ID }}
          private-key: ${{ secrets.MADDERFERRYS_PRIVATE_KEY }}
      - name: Update release state
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          target-branch: ${{ github.ref_name }}
