---
name: Release Please
on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    types:
      - completed
    branches:
      - main
    workflows:
      - Action / Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  update:
    name: Update release state
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        with:
          app-id: ${{ vars.MADDERFERRYS_APP_ID }}
          private-key: ${{ secrets.MADDERFERRYS_PRIVATE_KEY }}
      - name: Update release state
        uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          target-branch: ${{ github.ref_name }}
