---
name: treefmt
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  format:
    name: Format changes
    if: ${{ github.event.sender.login != 'the-accuser[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Lix
        uses: fabrictest/action-setup-lix@b0d6d18b6c0d22639d5a3bd3f6454dab2f61f04c # v0.13.0
        with:
          lix-on-tmpfs: true
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ vars.CACHIX_NAME }}
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Format files
        id: format
        # TODO(eff): Switch to --ci when running on commits by TheAccuser.
        run: |
          nix develop --command treefmt
          {
            echo files'<<'FILES
            git diff --name-only
            echo FILES
          } >>"$GITHUB_OUTPUT"
        shell: bash
      - name: Generate app token
        if: ${{ !cancelled() && steps.format.outputs.files }}
        id: app-token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        with:
          app-id: ${{ vars.THE_ACCUSER_APP_ID }}
          private-key: ${{ secrets.THE_ACCUSER_PRIVATE_KEY }}
      - name: Commit changes
        if: ${{ !cancelled() && steps.format.outputs.files }}
        uses: IAreKyleW00t/verified-bot-commit@dc18a0710cb31181d9e3e0e3adca7206e0d39258 # v1.0.11
        with:
          files: ${{ steps.format.outputs.files }}
          message: |
            style: format changes
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
