---
name: treefmt
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  format:
    name: Format changes
    runs-on: ubuntu-latest
    steps:
      - name: Install Lix
        uses: fabrictest/action-setup-lix@b0d6d18b6c0d22639d5a3bd3f6454dab2f61f04c # v0.13.0
        with:
          lix-on-tmpfs: true
      - name: Set up Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Format files
        run: |
          nix develop -c treefmt --no-cache --fail-on-change
        shell: bash
      - name: List modified files
        if: ${{ failure() && github.event.sender.login != 'the-accuser[bot]' }}
        id: files-to-commit
        run: |
          {
            echo list'<<'LIST
            git diff --name-only
            echo LIST
          } >>"$GITHUB_OUTPUT"
        shell: bash
      - name: Generate app token
        if: ${{ failure() && steps.files-to-commit.outputs.list }}
        id: app-token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        with:
          app-id: ${{ vars.THE_ACCUSER_APP_ID }}
          private-key: ${{ secrets.THE_ACCUSER_PRIVATE_KEY }}
      - name: Commit changes
        if: ${{ failure() && steps.files-to-commit.outputs.list }}
        uses: IAreKyleW00t/verified-bot-commit@dc18a0710cb31181d9e3e0e3adca7206e0d39258 # v1.0.11
        with:
          files: ${{ steps.files-to-commit.outputs.list }}
          message: |
            style: format changes
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
