---
name: zizmor
on:
  push:
    paths:
      - ".github/workflows/**.yaml"
      - "**/action.yaml"
jobs:
  scan:
    name: Scan workflows and actions
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Run zizmor
        run: |
          pipx run -- zizmor --format=sarif --persona=pedantic . >zizmor.sarif
        shell: bash
        env:
          GH_HOST: github.com
          GH_TOKEN: ${{ github.token }}
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1
        with:
          category: zizmor
          sarif_file: zizmor.sarif
