---
name: zizmor
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - ".github/workflows/**.yaml"
      - "**/action.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**.yaml"
      - "**/action.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  lint:
    name: Lint GitHub actions and workflows
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Lint Github actions and workflows
        run: |
          pipx run --quiet -- \
              zizmor --quiet --format=sarif --gh-hostname="${GITHUB_SERVER_URL#*://}" --persona=auditor . >"$sarif_file"
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          sarif_file: ${{ runner.temp }}/${{ github.workflow }}.sarif
      - name: Upload SARIF report to GitHub
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3.28.10
        with:
          category: ${{ github.workflow }}
          sarif_file: ${{ runner.temp }}/${{ github.workflow }}.sarif
