---
name: release-please-done
author: F. Emerson
description: |
  Marks a pull request opened by Release Please as published.
  This event marks the end of the release process.

  Required permissions:

  - `pull-requests`: `write`
inputs:
  repository:
    description: |
      Repository where the release process took place.
    default: ${{ github.repository }}
  tag:
    description: |
      Name of the release tag.
    required: true
  token:
    description: |
      Token to authenticate to the GitHub API.
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Retrieve PR
      id: pr
      run: |
        gh pr list \
            -L 1 \
            -S "$tag"' is:merged label:"autorelease: tagged" sort:created-desc' \
            -t '{{range .}}number={{.number}}{{"\n"}}{{end}}' \
            --json number >>"$GITHUB_OUTPUT"
      shell: bash
      env:
        GH_REPO: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
        tag: ${{ inputs.tag }}
    - name: Mark PR as published
      if: ${{ steps.pr.outputs.number }}
      run: |
        gh pr edit "$pr" \
          --remove-label 'autorelease: tagged' \
          --add-label 'autorelease: published'
      shell: bash
      env:
        GH_REPO: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
        pr: ${{ steps.pr.outputs.number }}
